version: 2.1
commands:

jobs:
  frontend-build-and-deploy-to-gcp:
    working_directory: ~/frontend_build
    docker:
      - image: 3apag/ci-node:10.16
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Client - Install Next.js
          working_directory: ~/frontend_build/packages/client
          command: yarn
      - run:
          name: Client - Build Next.js
          working_directory: ~/frontend_build/packages/client
          command: yarn run build
      - run:
          name: Client UI - Create Docker Image
          working_directory: ~/frontend_build/
          command: |
            IMAGE=admin-ui-service
            docker build -t client-image .

workflows:
  version: 2
  fronted-workflows:
    jobs:
      - frontend-build-and-deploy-to-gcp
