version: 2.1
commands:
  cmd-fe-save-cache:
    description: Store npm cache
    steps:
      - save_cache:
          key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - client/node_modules

  cmd-fe-restore-cache:
    description: Restore npm cache
    steps:
      - restore_cache:
          keys:
            - yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}

  cmd-fe-npm-install-dependencies:
    description: Frontend Workspaces - Install dependencies using cached npm resources.
    parameters:
      service:
        type: string
    steps:
      - run:
          name: << parameters.service >> - Install dependencies
          # working_directory: << parameters.working_directory >>
          command: yarn install

jobs:
  frontend-build-test:
    working_directory: ~/frontend_build
    docker:
      - image: 3apag/ci-node:10.16
    steps:
      - checkout
      - cmd-fe-restore-cache
      - cmd-fe-npm-install-dependencies:
          service: Frontend Workspaces
          # working_directory: ~/frontend_build
      - run:
          name: Client - Build Next.js
          working_directory: packages/client
          command: yarn run build
      - cmd-fe-save-cache

workflows:
  version: 2
  fronted-workflows:
    jobs:
      - frontend-build-test
